#%RAML 1.0
title: Weather Service API
version: v1
baseUri: http://localhost:8082

/countries:
  /{country}:
    /cities:
      displayName: Cities by country
      description: Get the names of the cities for given country
      get:
        responses:
          200:
            body:
              application/json:
                example: !include examples/countries/cities/cities.json
      /{city}:
        /weather:
          displayName: Weather by city
          description: Get weather data for given city
          get:
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/countries/cities/weather/weather.json 
    
